[package]
name = "brctl"
version = "0.0.1"
author = "Elvin Bajric <elvin.bajricc@gmail.com>"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
glob = "0.3.1"
